---
version: 5.0.0
basic_settings:
  filter_statements:
    movie:
      played:
        condition_days: -1
        count_equality: '>='
        count: 1
      created:
        condition_days: -1
        count_equality: '>='
        count: 1
        behavioral_control: true
    episode:
      played:
        condition_days: -1
        count_equality: '>='
        count: 1
      created:
        condition_days: -1
        count_equality: '>='
        count: 1
        behavioral_control: true
    audio:
      played:
        condition_days: -1
        count_equality: '>='
        count: 1
      created:
        condition_days: -1
        count_equality: '>='
        count: 1
        behavioral_control: true
advanced_settings:
  behavioral_statements:
    movie:
      favorited:
        action: keep
        user_conditional: any
        played_conditional: ignore
        action_control: 3
        advanced:
          genre: 0
          library_genre: 0
      whitetagged:
        action: keep
        user_conditional: all
        played_conditional: ignore
        action_control: 0
        tags: []
      blacktagged:
        action: delete
        user_conditional: all
        played_conditional: any_played
        action_control: 0
        tags: []
      whitelisted:
        action: keep
        user_conditional: any
        played_conditional: ignore
        action_control: 3
      blacklisted:
        action: delete
        user_conditional: any
        played_conditional: any_played
        action_control: 3
    episode:
      favorited:
        action: keep
        user_conditional: any
        played_conditional: ignore
        action_control: 3
        advanced:
          genre: 0
          season_genre: 0
          series_genre: 0
          library_genre: 0
          studio_network: 0
          studio_network_genre: 0
      whitetagged:
        action: keep
        user_conditional: all
        played_conditional: ignore
        action_control: 0
        tags: []
      blacktagged:
        action: delete
        user_conditional: all
        played_conditional: any_played
        action_control: 0
        tags: []
      whitelisted:
        action: keep
        user_conditional: any
        played_conditional: ignore
        action_control: 3
      blacklisted:
        action: delete
        user_conditional: any
        played_conditional: any_played
        action_control: 3
    audio:
      favorited:
        action: keep
        user_conditional: any
        played_conditional: ignore
        action_control: 3
        advanced:
          genre: 0
          album_genre: 0
          library_genre: 0
          track_artist: 0
          album_artist: 0
      whitetagged:
        action: keep
        user_conditional: all
        played_conditional: ignore
        action_control: 0
        tags: []
      blacktagged:
        action: delete
        user_conditional: all
        played_conditional: any_played
        action_control: 0
        tags: []
      whitelisted:
        action: keep
        user_conditional: any
        played_conditional: ignore
        action_control: 3
      blacklisted:
        action: delete
        user_conditional: any
        played_conditional: any_played
        action_control: 3
  whitetags: []
  blacktags: []
  episode_control:
    minimum_episodes: 0
    minimum_played_episodes: 0
    minimum_episodes_behavior: Max Played Min Unplayed
  trakt_fix:
    set_missing_last_played_date:
      movie: true
      episode: true
      audio: true
  console_controls:
    headers:
      script:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      user:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      summary:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
    footers:
      script:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
    warnings:
      script:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
    movie:
      delete:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      keep:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      post_processing:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      summary:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
    episode:
      delete:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      keep:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      post_processing:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      summary:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
    audio:
      delete:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      keep:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      post_processing:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
      summary:
        show: true
        formatting:
          font:
            color: ''
            style: ''
          background:
            color: ''
  UPDATE_CONFIG: false
  REMOVE_FILES: false
admin_settings:
  server:
    brand: emby
    url: http://172.31.14.123:39647/emby
    auth_key: d79729c429e14f8c8a504679e40c4dc7
  behavior:
    list: blacklist
    matching: byId
  users:
  - user_id: 4c03eed461624bb9bf8bcc5a4515e2ef
    user_name: Guest.User
    whitelist:
    - libid: f137a2dd21bbc1b99aa5c0f6bf02a805
      collectiontype: movies
      path: /media/Pharaoh/xbmc/Movies
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Movies
      selection: 0
    - libid: 4514ec850e5ad0c47b58444e17b6346c
      collectiontype: tvshows
      path: /media/Pharaoh/xbmc/TV
      networkpath: smb://hieroglyph/Pharaoh/xbmc/TV
      selection: 1
    blacklist:
    - libid: ''
      collectiontype: ''
      path: ''
      networkpath: ''
      selection: -1
  - user_id: e65f93a452104325ae8c92f3db0983f5
    user_name: Hieroglyph.Admin
    whitelist:
    - libid: 48af3bb0f5988d3cd867a245b7ef32d1
      collectiontype: audiobooks
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 0
    - libid: 4514ec850e5ad0c47b58444e17b6346c
      collectiontype: tvshows
      path: /media/Pharaoh/xbmc/TV
      networkpath: smb://hieroglyph/Pharaoh/xbmc/TV
      selection: 4
    blacklist:
    - libid: 4e985111ed7f570b595204d82adb02f3
      collectiontype: books
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 1
    - libid: f137a2dd21bbc1b99aa5c0f6bf02a805
      collectiontype: movies
      path: /media/Pharaoh/xbmc/Movies
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Movies
      selection: 2
    - libid: 7e64e319657a9516ec78490da03edccb
      collectiontype: music
      path: /media/Pharaoh/xbmc/Music/Albums
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Albums
      selection: 3
  - user_id: 936055badcd3462aa4fa9cc1f6e42e7f
    user_name: LaLa.User
    whitelist:
    - libid: 48af3bb0f5988d3cd867a245b7ef32d1
      collectiontype: audiobooks
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 0
    - libid: 4e985111ed7f570b595204d82adb02f3
      collectiontype: books
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 1
    - libid: 4514ec850e5ad0c47b58444e17b6346c
      collectiontype: tvshows
      path: /media/Pharaoh/xbmc/TV
      networkpath: smb://hieroglyph/Pharaoh/xbmc/TV
      selection: 3
    blacklist:
    - libid: f137a2dd21bbc1b99aa5c0f6bf02a805
      collectiontype: movies
      path: /media/Pharaoh/xbmc/Movies
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Movies
      selection: 2
  - user_id: 97fbc9cf21724e4eb30bd2fb9268559d
    user_name: Terrel.User
    whitelist:
    - libid: 48af3bb0f5988d3cd867a245b7ef32d1
      collectiontype: audiobooks
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 0
    - libid: 4e985111ed7f570b595204d82adb02f3
      collectiontype: books
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 1
    blacklist:
    - libid: 7e64e319657a9516ec78490da03edccb
      collectiontype: music
      path: /media/Pharaoh/xbmc/Music/Albums
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Albums
      selection: 3
    - libid: f137a2dd21bbc1b99aa5c0f6bf02a805
      collectiontype: movies
      path: /media/Pharaoh/xbmc/Movies
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Movies
      selection: 2
    - libid: 4514ec850e5ad0c47b58444e17b6346c
      collectiontype: tvshows
      path: /media/Pharaoh/xbmc/TV
      networkpath: smb://hieroglyph/Pharaoh/xbmc/TV
      selection: 4
  - user_id: faa2815c4b0043fd9ecade45b66a0f12
    user_name: user1
    whitelist:
    - libid: f137a2dd21bbc1b99aa5c0f6bf02a805
      collectiontype: movies
      path: /media/Pharaoh/xbmc/Movies
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Movies
      selection: 2
    - libid: 4514ec850e5ad0c47b58444e17b6346c
      collectiontype: tvshows
      path: /media/Pharaoh/xbmc/TV
      networkpath: smb://hieroglyph/Pharaoh/xbmc/TV
      selection: 4
    blacklist:
    - libid: 7e64e319657a9516ec78490da03edccb
      collectiontype: music
      path: /media/Pharaoh/xbmc/Music/Albums
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Albums
      selection: 3
    - libid: 4e985111ed7f570b595204d82adb02f3
      collectiontype: books
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 1
    - libid: 48af3bb0f5988d3cd867a245b7ef32d1
      collectiontype: audiobooks
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 0
  - user_id: 804d91d6ca044caaa298eb0cb69a4ceb
    user_name: user2
    whitelist:
    - libid: ''
      collectiontype: ''
      path: ''
      networkpath: ''
      selection: -1
    blacklist:
    - libid: 48af3bb0f5988d3cd867a245b7ef32d1
      collectiontype: audiobooks
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 0
    - libid: 4e985111ed7f570b595204d82adb02f3
      collectiontype: books
      path: /media/Pharaoh/xbmc/Books
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Books
      selection: 1
    - libid: 7e64e319657a9516ec78490da03edccb
      collectiontype: music
      path: /media/Pharaoh/xbmc/Music/Albums
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Albums
      selection: 3
    - libid: 4514ec850e5ad0c47b58444e17b6346c
      collectiontype: tvshows
      path: /media/Pharaoh/xbmc/TV
      networkpath: smb://hieroglyph/Pharaoh/xbmc/TV
      selection: 4
    - libid: f137a2dd21bbc1b99aa5c0f6bf02a805
      collectiontype: movies
      path: /media/Pharaoh/xbmc/Movies
      networkpath: smb://hieroglyph/Pharaoh/xbmc/Movies
      selection: 2
  api_controls:
    attempts: 4
    item_limit: 25
  cache:
    size: 32
    fallback_behavior: LRU
    last_accessed_time: 200
DEBUG: 0
...